=== anton2larionov/bsuir-labs/oop/src/main/resources/medicaments.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema
        xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="catalogue"
        xmlns:c="catalogue"
        attributeFormDefault="qualified"
        elementFormDefault="qualified">

    <element name="catalogue">
        <complexType>
            <sequence>
                <element ref="c:medicament" maxOccurs="unbounded" minOccurs="0"/>
            </sequence>
        </complexType>
    </element>

    <element name="medicament">
        <complexType>
            <sequence>
                <element name="title" type="c:TitleType"/>
                <element name="on-prescription" type="boolean"/>
                <element name="purchase-date" type="date"/>
                <element name="description" type="c:DescriptionType" maxOccurs="1" minOccurs="0"/>
            </sequence>
            <attribute type="ID" name="id" use="required"/>
            <attribute type="c:DiscountType" name="discount" use="optional"/>
        </complexType>
    </element>

    <simpleType name="TitleType">
        <restriction base="string">
            <pattern value="[A-Z]{1}\w{2,49}"/>
        </restriction>
    </simpleType>

    <simpleType name="DescriptionType">
        <restriction base="string">
            <maxLength value="1000"/>
        </restriction>
    </simpleType>

    <simpleType name="DiscountType">
        <restriction base="string">
            <enumeration value="regular"/>
            <enumeration value="promotion"/>
        </restriction>
    </simpleType>

</schema>

=== anton2larionov/bsuir-labs/oop/src/main/resources/medicaments.xml
<?xml version="1.0" encoding="UTF-8"?>
<c:catalogue
        xmlns:c="catalogue"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="catalogue medicaments.xsd ">
    <c:medicament c:id="id1">
        <c:title>Ascorutin</c:title>
        <c:on-prescription>false</c:on-prescription>
        <c:purchase-date>2013-11-30</c:purchase-date>
        <c:description>Аскорутин уменьшает проницаемость и ломкость капилляров.</c:description>
    </c:medicament>
    <c:medicament c:id="id2" c:discount="regular">
        <c:title>Spasmalgon</c:title>
        <c:on-prescription>true</c:on-prescription>
        <c:purchase-date>2015-06-12</c:purchase-date>
        <c:description>Комбинированный анальгетик с ярко выраженной спазмолитической активностью.</c:description>
    </c:medicament>
    <c:medicament c:id="id3" c:discount="promotion">
        <c:title>Choludexan</c:title>
        <c:on-prescription>true</c:on-prescription>
        <c:purchase-date>2016-03-07</c:purchase-date>
        <c:description>Стабилизирует мембраны гепатоцитов и холангиоцитов, оказывает прямое цитопротективное действие.
        </c:description>
    </c:medicament>
    <c:medicament c:id="id4">
        <c:title>Festal</c:title>
        <c:on-prescription>false</c:on-prescription>
        <c:purchase-date>2016-01-30</c:purchase-date>
    </c:medicament>
    <c:medicament c:id="id5" c:discount="regular">
        <c:title>Smecta</c:title>
        <c:on-prescription>false</c:on-prescription>
        <c:purchase-date>2015-09-21</c:purchase-date>
        <c:description>Оказывает адсорбирующее действие.</c:description>
    </c:medicament>
</c:catalogue>
